## Importing pandas

In [36]:
from calendar import month

import pandas as pd

In [37]:
df = pd.read_csv("netflix_titles.csv/netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [38]:
print(df.isnull().sum())
print("----------------")
print(df.duplicated().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64
----------------
0

In [39]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [40]:
df["director"] = df["director"].fillna("Unknown")

In [41]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            825
country         831
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

In [42]:
no_direct = df["director"] == "Unknown"
print(df.loc[no_direct, ["type", "title", "director"]])

         type                                title director
1     TV Show                        Blood & Water  Unknown
3     TV Show                Jailbirds New Orleans  Unknown
4     TV Show                         Kota Factory  Unknown
10    TV Show  Vendetta: Truth, Lies and The Mafia  Unknown
14    TV Show      Crime Stories: India Detectives  Unknown
...       ...                                  ...      ...
8795  TV Show                      Yu-Gi-Oh! Arc-V  Unknown
8796  TV Show                           Yunus Emre  Unknown
8797  TV Show                            Zak Storm  Unknown
8800  TV Show                   Zindagi Gulzar Hai  Unknown
8803  TV Show                          Zombie Dumb  Unknown

[2634 rows x 3 columns]

In [43]:
df = df.apply(lambda x: x.strip() if x.dtype == "object" else x)

In [44]:
df = df[df["type"] == "Movie"]

In [45]:
df["rating"].unique()

<StringArray>
[   'PG-13',       'PG',    'TV-MA',    'TV-PG',    'TV-14',     'TV-Y',
        'R',     'TV-G',    'TV-Y7',        'G',    'NC-17',   '74 min',
   '84 min',   '66 min',       'NR',        nan, 'TV-Y7-FV',       'UR']
Length: 18, dtype: str

In [52]:
mask = df["rating"].str.contains("min", na=False)
df.loc[mask,"duration"] = df.loc[mask,"rating"]
df.loc[mask, "rating"] = pd.NA

In [63]:
print(df.loc[mask, ["show_id", "type","rating","duration"]])

     show_id   type rating duration
5541   s5542  Movie    NaN   74 min
5794   s5795  Movie    NaN   84 min
5813   s5814  Movie    NaN   66 min

In [79]:
df[df["show_id"] == "s5542"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,NaN,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."

In [78]:
df.dtypes

show_id                    str
type                       str
title                      str
director                   str
cast                       str
country                    str
date_added      datetime64[us]
release_year             int64
rating                     str
duration                   str
listed_in                  str
description                str
dtype: object

In [77]:
df["date_added"] = pd.to_datetime(df["date_added"])